spring.application.name=slaughterhouse-grpc-server
spring.datasource.url=jdbc:postgresql://localhost:5432/slaughterhouse
spring.datasource.username=postgres
spring.datasource.password=mike
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
